config/routes.rb
Rails.application.routes.draw do
  root 'characters#new'

  get 'intro' => 'characters#intro', as: :intro

  resources :characters
  resources :stories

  # Front-End Playable Routes
  get 'characters/:character_id/:story_id' => 'stories#show', as: :play_story
  get 'characters/:character_id/:story_id/:branch_id' => 'stories#play_branch', as: :play_branch

  # Qualities Routes
  resources :qualities
end

app/models/quality.rb
class Quality < ActiveRecord::Base
  has_many :requirements, :dependent => :destroy
  has_many :stats, :dependent => :destroy
  has_many :levels, :dependent => :destroy
  accepts_nested_attributes_for :levels,
                                reject_if: :all_blank,
                                allow_destroy: true
  delegate :name, to: :requirements, prefix: true # Not entirely sure this is necessary anymore. Maybe delete.
  validates :name,
            presence: true,
            length: { minimum: 3}
  validates :description,
            presence: true,
            length: { minimum: 5}
  validates :image_path,
            allow_blank: true,
            length: { minimum: 3}
  validates :category,
            presence: true

  def find_by_name(quality_name)
    Quality.where(name: quality_name).first
  end

end

app/controllers/qualities_controller.rb
class QualitiesController < ApplicationController
  def index
    @qualities = Quality.all
  end

  def show
    @quality = Quality.find(params[:id])
    @qualities = [Quality.find(params[:id])]
  end

  def new
    @quality = Quality.new
    @quality.levels.build
  end
  
  def edit
    @quality = Quality.find(params[:id])
    @level = 1
  end
  
  def create
    if Quality.where(name: quality_params[:name]).count > 0
      @quality = Quality.where(name: quality_params[:name]).first
      redirect_to @quality
    else
    @quality = Quality.new(quality_params)
      if  @quality.save
        redirect_to qualities_path
      else
        render 'new'
      end
    end
  end
  
  def update
    @quality = Quality.find(params[:id])
    
    if @quality.update(quality_params)
      flash[:notice] = "Successfully updated the Quality."
      redirect_to qualities_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @quality = Quality.find(params[:id])
    @quality.destroy
    
    redirect_to qualities_path
  end
  
  private
  def quality_params
    params.require(:quality).permit(:name, :description, :image_path, :ranked, :category,
                                    levels_attributes:[ :id, :quality_id, :amount, :description, :image_path, :minimum_points, :flavor_text, :_destroy])
  end
end

app/helpers/qualities_helper.rb
module QualitiesHelper
end

app/views/qualities/_level_fields.html.haml
%tr.level_fields
  %td
    = @level.to_s
    = @level = 1 if @level.blank?
    = f.hidden_field(:rank, :value => params[@level.to_s])
  %td
    = f.text_field :description
  %td
    = f.text_field :image_path
  %td
    = f.text_area :flavor_text
  %td
    = f.text_field :minimum_points
  %td
    = link_to_remove_association('Delete Level', f, {wrapper_class: 'level_fields'})
- @level = @level.next

app/views/qualities/_qualityform.html.haml
= form_for @quality do |quality|
  #quality_form_wrapper
    = render 'qualityformerrors'
    %p
      = quality.label :name
      = quality.text_field :name
    %p
      = quality.label :description
      = quality.text_area :description
    %p
      = quality.label :image_path
      = quality.text_field :image_path
    %p
      = quality.label :category
      = quality.select(:category, [["Primary", "Primary"], ["Secondary","Secondary"], ["Story","Story"], ["Item","Item"], ["Fate Deck","Fate Deck"]])
    %p
      = quality.label :is_this_quality_have_a_level_progression?
      = quality.check_box :ranked
    %p
    %p
      = quality.submit "Update", :id => "quality_submit_button"
  #level_form_wrapper
    %table.levels_table
      %tr
        %th#level Level
        %th#description Description
        %th#image_path Image Path
        %th#flavor_text Flavor Text
        %th#minimum_points Minimum Points
        %th#action Action
      = quality.fields_for :levels do |f|
        = render 'level_fields', :f => f
    = link_to_add_association "+ Add Level", quality, :levels, 'data-association-insertion-node' => ".levels_table", 'data-association-insertion-method' => "append"

app/views/qualities/_qualityformerrors.html.haml
- if @quality.errors.any?
  #error_explanation
    %ul
      - @quality.errors.full_messages.each do |msg|
        %li= msg

app/views/qualities/_qualitytable.html.haml
%table
  %tr
    %th Key
    %th Name
    %th Category
    %th Description
    %th Image Path
    %th Actions
  - @qualities.each do |quality|
    %tr
      %td= quality.id
      %td= quality.name
      %td= quality.category
      %td
        = quality.description
        - quality.levels.each do |level|
          %p
            = level.rank
            \. #{level.description}
      %td= image_pack_tag "icons/#{quality.image_path}", :class => "large_icon"
      %td
        = link_to 'Edit', edit_quality_path(quality)
        ,
        \#{link_to 'Destroy', quality_path(quality), method: :delete, data: { confirm: 'Are you sure?' }}

app/views/qualities/edit.html.haml
= render "/layouts/backend_navigation"
%h1 Edit Quality
= render 'qualityform'

app/views/qualities/index.html.haml
= render "/layouts/backend_navigation"
- if flash[:notice]
  %p.notice= flash[:notice]
%h1 Existing Qualities
%p= link_to 'Create New Quality', new_quality_path
= render 'qualitytable'

app/views/qualities/new.html.haml
= render "/layouts/backend_navigation"
%h1 Add a New Quality
= render 'qualityform'

app/views/qualities/show.html.haml
= render "/layouts/backend_navigation"
%p
  You have successfully created the quality: #{@quality.name}
= render 'qualitytable'
%p= link_to 'Show All Qualities', qualities_path
%p= link_to 'Go to Stories', stories_path