config/routes.rb
Rails.application.routes.draw do
  root 'characters#new'

  get 'intro' => 'characters#intro', as: :intro

  resources :characters
  resources :stories

  # Front-End Playable Routes
  get 'characters/:character_id/:story_id' => 'stories#show', as: :play_story
  get 'characters/:character_id/:story_id/:branch_id' => 'stories#play_branch', as: :play_branch

  # Qualities Routes
  resources :qualities
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_reader :eligible_stories
  has_many :branches, :dependent => :destroy
  has_many :requirements, :dependent => :destroy
  has_many :fate_cards, :dependent => :destroy
  accepts_nested_attributes_for :branches, 
                                :reject_if => :all_blank,
                                :allow_destroy => true
  accepts_nested_attributes_for :requirements, 
                                :reject_if => :all_blank, 
                                :allow_destroy => true
  validates :title, 
            length: { minimum: 3}
  validates :hook, 
            allow_blank: true,
            length: { minimum: 5}
  validates :body, 
            allow_blank: true,
            length: { minimum: 5}
  validates :image_path, 
            allow_blank: true,
            length: { minimum: 3}
  validates :location, 
            length: { minimum: 3}

  def eligible?(character)
    Eligible.new(character, self).eligibility
  end

  def eligible_stories(character, set_of_stories)
    stories = []
    set_of_stories.each do |story|  
      if story.eligible?(character) && (story.character_in_story_location?(character) || story.location == "Fate Card")
        stories.push(story)
      end
    end
    stories
  end

  def character_in_story_location?(character)
    character.location.description == self.location
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
before_action :find_story, only: [:show, :edit, :update, :destroy, :destroy_requirement]
before_action :find_character, only: [:show, :play_branch]
before_action :locations, only: [:new, :edit, :update]

  def find_story
    @story = Story.find(params[:story_id])
    @branches = @story.branches
  end

  def find_character
    unless params[:character_id].nil?
      @character = Character.find(params[:character_id])
    end
  end

  def locations
    @locations = ["Fate Card"]
      Quality.find_by(:name => "Location").levels.each do |k|
        @locations.push(k.description)
      end
    @locations
  end

  def play_branch
    @branch = Branch.find(params[:branch_id])
    if @branch.story.location == "Fate Card"
      @branch.story.fate_cards.where(:story_id => @branch.story.id, :character_id => @character.id).first.destroy
    end
    @stat_outcomes = @branch.execute_branch_effects(@character) unless @character.nil?
  end
  
  def index
    @stories = Story.all
  end

  def show
  end

  def new
    @story = Story.new
    @story.requirements.build
    @story.branches.build
    @requirements = @story.requirements
  end
  
  def edit
  end
  
  def create
    @story = Story.new(story_params)
    if  @story.save
    redirect_to :action => 'edit', :story_id => @story.id
    else
      render 'edit'
    end
  end
  
  def update
    if @story.update(story_params)
      redirect_to :action => 'edit', :story_id => @story.id
    else
      render 'edit'
    end
  end
  
  def destroy
    @story.destroy
    redirect_to stories_path
  end
  
  private
  def story_params
    params.require(:story).permit(:title, :body, :image_path, :hook, :location,
                                  requirements_attributes:[ :id, :quality_id, :points , :operation, :_destroy ],
                                  branches_attributes:[ :id, :title, :description, :outcome, :_destroy,  
                                    branch_requirements_attributes:[ :id, :branch_id, :quality_id, :points, :operation, :_destroy ],
                                    effects_attributes:[ :id, :branch_id, :quality_id, :operation, :amount, :_destroy] ])
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_branch_fields.html.haml
.branch_card
  .branch_card_left_column
    %p
      %b= f.label :Title
      = f.text_field :title
    %p
      %b= f.label :Image_path
      = f.text_field :image_path
    %p
      %b= f.label :Hook
      = f.text_area :description, :class => "hook"
    %p
      %b= f.label :Outcome
      = f.text_area :outcome
    %br/
  .branch_card_right_column
    = render 'branch_requirementform', :f => f
    .effectform
      %h3 Branch Effects
      %table{:id => "effects-table-#{"#{f.object.id}"}"}
        %tr
          %th Quality Required
          %th Operation
          %th Amount
          %th Actions
        = f.fields_for :effects do |effect|
          = render 'effect_fields', :f => effect
      = link_to_add_association 'Add Effect', f, :effects, 'data-association-insertion-node' => "#effects-table-#{f.object.id}",'data-association-insertion-method' => "append"
  #update_branch
    = f.button :submit, name: "story_id", value: @story.id
    %br/
    %br/
    = link_to_remove_association('Delete Branch', f, { wrapper_class: 'branch_card'})

app/views/stories/_branch_requirement_fields.haml
%tr.nested-fields
  %td
    = f.select(:quality_id, Quality.all.collect {|q| [ q.name, q.id ] }, { include_blank: true })
  %td
    = f.select(:operation, [['at least','at least'], ['less than','less than'],['is','is'], ['is not','is not']], { include_blank: true })
  %td
    = f.text_field :points
  %td
    = link_to_remove_association "Delete", f

app/views/stories/_branch_requirementform.html.haml
.branch-requirementform
  %h3 Requirements
  %table{:id => "branch-requirements-table-#{"#{f.object.id}"}"}
    %tr
      %th Quality Required
      %th Operation
      %th Points
      %th Actions
    = f.fields_for :branch_requirements do |branch_requirement|
      = render 'requirement_fields', :f => branch_requirement
  = link_to_add_association 'Add Requirement', f, :branch_requirements, 'data-association-insertion-node' => "#branch-requirements-table-#{f.object.id}",'data-association-insertion-method' => "append"

app/views/stories/_effect_fields.haml
%tr.nested-fields
  %td
    = f.select(:quality_id, Quality.all.collect {|q| [ q.name, q.id ] }, { include_blank: true })
  %td
    = f.select(:operation, [['plus','plus'], ['minus','minus'],['equals','equals']], { include_blank: true })
  %td
    = f.text_field :amount
  %td
    = link_to_remove_association "Delete", f

app/views/stories/_play_branch_card.html.haml
- @branches.each do |branch|
  %div{:class => "play_branch_card eligibility_#{branch.eligible?(@character)}"}
    .play_branch_card_top
      %h4= branch.title
      = branch.image_path
      %p= branch.description
    .play_branch_card_bottom
      - if branch.eligible?(@character)
        = button_to "Go", play_branch_path(:branch_id => branch.id), :class => "go_button", :method => "get"
      - unless branch.branch_requirements.empty?
        .requirement_description
          %p
            %i
              Requires
              - branch.branch_requirements.each_with_index do |requirement, index|
                - if index != 0
                  and
                = requirement.quality.name
                = requirement.get_level.rank if requirement.get_level.present?

app/views/stories/_requirement_fields.haml
%tr.nested-fields
  %td
    = f.select(:quality_id, Quality.all.collect {|q| [ q.name, q.id ] }, { include_blank: true })
  %td
    = f.select(:operation, [['at least','at least'], ['less than','less than'],['is','is'], ['is not','is not']], { include_blank: true })
  %td
    = f.text_field :points
  %td
    = link_to_remove_association "Delete", f

app/views/stories/_storyform.html.haml
= form_for @story do |story|
  = render 'storyformerrors'
  #storyform_and_requirementform_wrapper
    #storyform
      %p
        = story.label :title
        = story.text_field :title
      %p
        = story.label :image_path
        = story.text_field :image_path
      %p
        = story.label :hook
        = story.text_area :hook, :class => "hook"
      %p
        = story.label :body
        = story.text_area :body
      = story.label :story_location
      = story.select :location, options_for_select(@locations, @story.location)
    = render 'requirementform', :f => story
    #submit_button= story.button :submit, name: "story_id", value: @story.id
  #branchform_wrapper
    %h2 Story Branches
    = story.fields_for :branches do |branch|
      = render 'branch_fields', :f => branch
    = link_to_add_association "+ Add Branch", story, :branches,'data-association-insertion-node' => "#add_branch_link", 'data-association-insertion-method' => "before", :id => "add_branch_link"

app/views/stories/_storyformerrors.html.haml
- if @story.errors.any?
  #error_explanation
    %ul
      - @story.errors.full_messages.each do |msg|
        %li= msg

app/views/stories/edit.html.haml
= render "/layouts/backend_navigation"
%h1 Edit Story
= render 'storyform'
%p
  = link_to "Back to Top", "#"
%p= link_to "Back to Stories Index", stories_path

app/views/stories/index.html.haml
= render "/layouts/backend_navigation"
%h1 Existing Stories
%table
  %tr
    %th Key
    %th Title
    %th Hook
    %th Text
    %th Location
    %th Actions
  - @stories.each do |story|
    %tr
      %td= story.id
      %td= story.title
      %td= truncate(story.hook, :length => 30)
      %td= truncate(story.body, :length => 60)
      %td= story.location
      %td
        = link_to 'Edit Story', edit_story_path(:story_id => story.id)
        ,
        \#{link_to 'Delete Story', story_path(:id => story.id, :story_id => story.id), method: :delete, data: { confirm: 'Are you sure?' }}
  %p= link_to 'Add a Story', new_story_path

app/views/stories/new.html.haml
= render "/layouts/backend_navigation"
%p
  ← #{link_to "Show Stories Index", stories_path}
%h1 New Story
= render 'storyform'

app/views/stories/play_branch.html.haml
= render layout: "/layouts/main_game" do
  %h1= @branch.title
  %p= @branch.outcome
  - unless @stat_outcomes.nil?
    %ul.outcomes_list
      - @stat_outcomes.each do |outcome|
        %li= outcome
  %p= button_to "Continue", character_path(), :method => 'get'
  - if @character.nil?
    %p= link_to 'Show All Stories', stories_path
    %p= link_to 'Show all Branches for All Stories', branches_path

app/views/stories/play_outcomes.html.erb
<%= render layout: "/layouts/main_game" do %>
  <h1><%= @branch.title %></h1>
  <p><%= @branch.outcome %></p>
  <% unless @stat_outcomes.nil? %>
    <ul class="outcomes_list">
    <% @stat_outcomes.each do |outcome| %>
        <li><%= outcome %></li>
    <% end %>
    </ul>
  <% end %>
  <p><%= link_to "Continue", character_path()%></p>

  <% if @character.nil? %>
    <p><%= link_to 'Show All Stories', stories_path %></p>
    <p><%= link_to 'Show all Branches for All Stories', branches_path %></p>
  <% end %>
<% end %>

app/views/stories/show.html.haml
= render layout: "/layouts/main_game" do
  = image_pack_tag "#{@story.image_path}", :class => "large_icon"
  %h2= @story.title
  %p= @story.body
  - unless @story.branches.nil?
    = render 'play_branch_card'
  = button_to "Return...", character_path, :method => :get