config/routes.rb
Rails.application.routes.draw do
  root 'characters#new'

  get 'intro' => 'characters#intro', as: :intro

  resources :characters
  resources :stories

  # Front-End Playable Routes
  get 'characters/:character_id/:story_id' => 'stories#show', as: :play_story
  get 'characters/:character_id/:story_id/:branch_id' => 'stories#play_branch', as: :play_branch

  # Qualities Routes
  resources :qualities
end

app/models/character.rb
class Character < ActiveRecord::Base
  ### Attributes ###################################################################################
  attr_writer :current_step
  attr_reader :deck_size

  ### Associations #################################################################################
  has_many :stats, dependent: :destroy
  has_many :fate_cards, dependent: :destroy

  ### Validations ##################################################################################
  validates :name, presence: true
  validates :avatar_image_path,
            presence: { message: 'Your vision is blurry and your hand-eye coordination is terrible, but you know you can do this. At least...you hope you can.' },
            if: ->(f) { f.current_step == 'avatar' }
  validates_presence_of :gender, if: lambda { |f|
                                       f.current_step == 'gender'
                                     }, message: 'Clearly deeply confused on the issue of your own gender and carrot-hood, but you somehow feel sure that if you just pick something, you can change your mind later and nobody will ever know.'
  ### Instance Methods #############################################################################
  def build_initial_character_stats
    character_location = Quality.find_by_name('Location')
    stats.create(quality_id: character_location.id, points: '1')
  end

  def get_stat(quality_name)
    quality = Quality.find_by_name(quality_name)
    stat = Stat.create_with(points: 1).find_or_create_by(quality_id: quality.id, character_id: id)
  end

  def location
    stat = get_stat('Location').get_level
  end

  def deck_size
    quality_id = Quality.find_by(name: 'Deck Size').id
    character_deck_stat = Stat.find_or_create_by(character: self, quality_id: quality_id)
    @deck_size = if character_deck_stat.points?
                   character_deck_stat.points
                 else
                   character_deck_stat.update(points: 3)
                 end
  end

  # Introduction's Form Wizard Logic
  def current_step
    @current_step || steps.first
  end

  def steps
    %w[intro name gender avatar final]
  end

  def next_step
    self.current_step = steps[steps.index(current_step) + 1]
  end

  def previous_step
    self.current_step = steps[steps.index(current_step) - 1]
  end

  def first_step?
    current_step == steps.first
  end

  def last_step?
    current_step == steps.last
  end

  def all_valid?
    steps.all? do |step|
      self.current_step = step
      valid?
    end
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :find_character, only: %i[show edit update destroy eligible_stories]

  def find_character
    @character = Character.find(params[:character_id])
  end

  def index
    @characters = Character.all
  end

  def show
    @fate_stories = FateCard.new.get_hand(@character)
    @stories = Story.new.eligible_stories(@character, Story.where.not(location: 'Fate Card'))
    @stats = @character.stats
  end

  def new
    session[:character_params] ||= {}
    @character = Character.new(session[:character_params])
    @character.current_step = session[:character_step]
  end

  def edit; end

  def create
    session[:character_params].deep_merge!(params[:character]) if params[:character]
    @character = Character.new(session[:character_params])
    @character.current_step = session[:character_step]
    if params[:back_button]
      @character.previous_step
    elsif @character.valid?
      if @character.last_step?
        @character.save if @character.all_valid?
      else
        @character.next_step
      end
    end
    session[:character_step] = @character.current_step
    if @character.new_record?
      render 'new'
    else
      session[:character_step] = session[:character_params] = nil
      @character.build_initial_character_stats
      redirect_to @character
    end
  end

  def update
    if @character.update(character_params)
      redirect_to @character
    else
      render 'edit'
    end
  end

  def destroy
    @character.destroy
    redirect_to characters_path
  end

  private

  def character_params
    params.require(:character).permit(:name, :gender, :avatar_image_path)
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_avatar_step.html.haml
#intro4
  %p The windows are grimy, but if you squint, you can make out your silhouette.
  %p
    You look like:
    %i (Select one)
  - @character.errors[:avatar_image_path].each do | msg |
    %p.error_message= msg
  - (1..12).each do |image|
    = image_pack_tag "avatar#{image}.png", :class => "avatar_icon_medium_selectable", :id => "avatar#{image}"
  = f.hidden_field :avatar_image_path, :value => ""

app/views/characters/_characterformerrors.html.haml
- if @character.errors.any?
  #error_explanation
    %ul
      - @character.errors.full_messages.each do |msg|
        %li= msg

app/views/characters/_characterstats.html.haml
- if @character.stats.count > 0
  - @character.stats.each do |stat|
    .character_stat
      = image_pack_tag("icons/#{stat.quality.image_path}", class:"medium_icon") unless stat.quality.image_path.blank?
      .character_stat_description
        = stat.get_description
        \.
- else
  %p YOU HAVE NOTHING.

app/views/characters/_final_step.html.haml
#intro5
  %p
    The train slowly grinds to a halt, making the lamps flicker as they dance to a standstill.
  %p
    The light from an exit far down the platform partially illuminates the tunnel, throwing long shadows against the ceiling arches.

app/views/characters/_gender_step.html.haml
#intro3
  %p You look into the window and see your reflection staring back. You are:
  #intro_radio_buttons
    = f.radio_button :gender, "female"
    = f.label :gender_female, "A woman. "
    %br/
    %br/
    = f.radio_button :gender, "male"
    = f.label :gender_male, "A man."
    %br/
    %br/
    = f.radio_button :gender, "neither"
    = f.label :gender_neither, "Exceptionally good-looking. The rest remains a mystery."
    %br/
    %br/
    = f.radio_button :gender, "asexual."
    = f.label :gender_asexual, "A sentient carrot."
  .error_messages
    - @character.errors[:gender].each do | msg |
      %p.error_message= msg
  %br/

app/views/characters/_header.html.haml
#intro_header
  %h1#intro_title THE LAST STATION

app/views/characters/_intro_step.html.haml
#intro1
  %p
    A loud, immediate mechanical rattling and whistling fills your ears. There is a searing pain in the back of your head. You open your eyes.
  %p
    There are six neat rows of leather seats, dark wood fixtures and brassy rails. You are in an old train carriage that is empty except for you.
  %p
    Outside the windows there is only darkness.

app/views/characters/_name_step.html.haml
#intro2
  %p The ache in your head begins to recede, but your memories are as shadowy as the world outside this train carriage.
  %p
    %b Your name is:
  = f.text_field :name
  .error_messages
    - @character.errors[:name].each do | msg |
      %p.error_message= msg
  %br/

app/views/characters/edit.html.haml
%h1 Edit Character Info
%p Henceforth, you shall be known as:
= form_for :character, url: character_path, method: :patch do |f|
  - render 'characterformerrors'
  %p
    = f.text_field :name
  .error_messages
    - @character.errors[:name].each do | msg |
      %p.error_message= msg
  %div
    = f.radio_button :gender, "female"
    = f.label :gender_female, "A woman. "
    %br/
    %br/
    = f.radio_button :gender, "male"
    = f.label :gender_male, "A man."
    %br/
    %br/
    = f.radio_button :gender, "neither"
    = f.label :gender_neither, "Exceptionally good-looking. The rest remains a mystery."
    %br/
    %br/
    = f.radio_button :gender, "carrot"
    = f.label :gender_carrot, "A sentient carrot."
  .error_messages
    - @character.errors[:gender].each do | msg |
      %p.error_message= msg
  %p
    You look like:
    %i (Select one)
  - @character.errors[:avatar_image_path].each do | msg |
    %p.error_message= msg
  - (1..12).each do |image|
    = image_pack_tag "avatar#{image}.png", :class => "avatar_icon_medium_selectable", :id => "avatar#{image}"
  = f.hidden_field :avatar_image_path, :value => ""
  %p
    = f.submit

app/views/characters/index.html.haml
%h1 Existing Characters
%table
  %tr
    %th Key
    %th Name
    %th Gender
    %th Actions
  - @characters.each do |character|
    %tr
      %td= character.id
      %td= character.name
      %td= character.gender
      %td
        = link_to 'Edit', edit_character_path(character)
        ,
        \#{link_to 'Destroy', character_path(character), method: :delete, data: { confirm: 'Are you sure?' }}

app/views/characters/new.html.haml
#wrapper
  = render partial: "header"
  #intro_body
    = render layout: "/layouts/flashcard" do
      = form_for @character do |f|
        = render "#{@character.current_step}_step", :f => f
        #flashcard_buttons
          = f.submit "Go back", :name => "back_button" unless @character.first_step?
          = "|" unless @character.first_step?
          = f.submit "Continue", :id => "continue_button"
  = render partial: "layouts/footer"

app/views/characters/show.html.haml
= render layout: "/layouts/main_game" do
  %h2= @character.location.description
  %p= @character.location.flavor_text
  - if @character.location.description == "The Station Exchange"
    %h3 The Hand of Fate...
    %p Click on a fate card to play it.
    %figure
      = image_pack_tag "story_card_back.png", :class => "fate_card_medium"
      %figcaption
        %b
          = @character.deck_size
          Cards Available
        %br/
        Additional Card in X mins.
    - @fate_stories.each do |fate_story|
      %figure
        = link_to image_pack_tag("#{fate_story.image_path}", :class => "fate_card_medium", :title => "#{fate_story.body}"), play_story_path(:story_id => fate_story.id), :method => :get
        %figcaption
          %b= fate_story.title
  %h3
    Play stories from #{@character.location.description}...
  %br/
  - @stories.each do |story|
    .story_card
      .story_card_left
        = image_pack_tag "icons/#{story.image_path}", :class => "large_icon"
      .story_card_middle
        %h4= story.title
        = story.hook
      .story_card_right
        = button_to 'Go', play_story_path(:story_id => story.id), class: "go_button", :method => :get