config/routes.rb
Rails.application.routes.draw do
  root 'characters#new'

  get 'intro' => 'characters#intro', as: :intro

  resources :characters
  resources :stories

  # Front-End Playable Routes
  get 'characters/:character_id/:story_id' => 'stories#show', as: :play_story
  get 'characters/:character_id/:story_id/:branch_id' => 'stories#play_branch', as: :play_branch

  # Qualities Routes
  resources :qualities
end

app/views/layouts/_backend_navigation.html.haml
#backend_navigation
  = link_to 'Stories Index', stories_path
  |
  \#{link_to 'Add a Story', new_story_path} ||
  \#{link_to 'Qualities Index', qualities_path} |
  \#{link_to 'Add a Quality', new_quality_path}

app/views/layouts/_flashcard.html.haml
#flashcard
  = image_pack_tag("divider.png", :class => "divider")
  #flashcard_body
    = yield
  = image_pack_tag("divider.png", :class => "bottom_divider")

app/views/layouts/_footer.html.haml
#footer
  #footer_center_div
    %p By Juliana Zhu

app/views/layouts/_header.html.haml
#main_header>
, style="background-image: url('/assets/#{@character.location.image_path}');"&gt;
%h1 THE LAST STATION

app/views/layouts/_main_game.html.haml
#player_interface_wrapper
  #main_game_wrapper
    = render partial: "layouts/header"
    #main_content_and_sidebar_wrapper
      = render partial: "layouts/sidebar"
      #main_content
        #main_content_top
        #main_content_middle
          #content_wrapper
            = yield
        #main_content_bottom

app/views/layouts/_sidebar.html.haml
#main_sidebar
  #sidebar_top_divider
    = image_pack_tag("divider.png", :class => "divider")
  #sidebar_content
    = image_pack_tag("#{@character.avatar_image_path}", :class => "avatar_icon_large", :id => "sidebar_avatar")
    #right_hand_wrapper
      %h4
        Welcome, #{@character.name}
    #main_stats_display
      = render 'characters/characterstats'
  #sidebar_bottom_divider
    = image_pack_tag("divider.png", :class => "bottom_divider")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TheLastStation
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #wrapper
      = yield